# Generated by Django 5.0.2 on 2024-02-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapi', '0003_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='batch',
        ),
    ]
