# Generated by Django 5.0.2 on 2024-02-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapi', '0004_remove_file_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('batch', models.CharField(max_length=3)),
                ('roll_no', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
