# Generated by Django 5.0.2 on 2024-04-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapi', '0006_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('std_id', 'lab_id', 'exp_id')},
        ),
    ]
